name: Push latest commit
on:
    push:
        branches: ["dev"]

jobs:
  update_branch_master:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest counter
        uses: actions/checkout@v3
      - name: Commit changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout master
          git merge dev 
        #   git commit -m "Automated: обновление репозитория"
        #   git push origin master
