name: Get latest blog posts
on:
    push:
        branches: ["dev"]

jobs:
  update_profile_data:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest counter
        uses: actions/checkout@v3
      - name: Commit changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Automated: обновление репозитория"
            git push origin master
          fi